# Generated by Django 4.2.15 on 2024-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0019_historicalpolicyholder_employer_tin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='employer_type',
            field=models.CharField(blank=True, db_column='EmployerType', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='employer_type',
            field=models.CharField(blank=True, db_column='EmployerType', max_length=128, null=True),
        ),
    ]
