# Generated by Django 4.2.15 on 2024-08-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0020_historicalpolicyholder_employer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpolicyholder',
            name='remarks',
            field=models.CharField(blank=True, db_column='Remarks', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='remarks',
            field=models.CharField(blank=True, db_column='Remarks', max_length=500, null=True),
        ),
    ]
